# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from lanelet_map_msgs/Regulatory.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import lanelet_map_msgs.msg
import geometry_msgs.msg

class Regulatory(genpy.Message):
  _md5sum = "6181abd984439c0ed4c1b41afc66d563"
  _type = "lanelet_map_msgs/Regulatory"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """Node[] special_nodes
Way[] special_ways

================================================================================
MSG: lanelet_map_msgs/Node
int32 id
string type
float64 vlimit
geometry_msgs/Point point

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: lanelet_map_msgs/Way
string task_area
int8 is_forward
int8 open_concave_obs_det
int8 open_dynamic_obs_det
int8 open_foggy_det
int8 open_water_det
int8 foggy_area
int8 lawn_area
int8 water_area
float64 vel_limit
Node[] points
"""
  __slots__ = ['special_nodes','special_ways']
  _slot_types = ['lanelet_map_msgs/Node[]','lanelet_map_msgs/Way[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       special_nodes,special_ways

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Regulatory, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.special_nodes is None:
        self.special_nodes = []
      if self.special_ways is None:
        self.special_ways = []
    else:
      self.special_nodes = []
      self.special_ways = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.special_nodes)
      buff.write(_struct_I.pack(length))
      for val1 in self.special_nodes:
        buff.write(_get_struct_i().pack(val1.id))
        _x = val1.type
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        buff.write(_get_struct_d().pack(val1.vlimit))
        _v1 = val1.point
        _x = _v1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.special_ways)
      buff.write(_struct_I.pack(length))
      for val1 in self.special_ways:
        _x = val1.task_area
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_get_struct_8bd().pack(_x.is_forward, _x.open_concave_obs_det, _x.open_dynamic_obs_det, _x.open_foggy_det, _x.open_water_det, _x.foggy_area, _x.lawn_area, _x.water_area, _x.vel_limit))
        length = len(val1.points)
        buff.write(_struct_I.pack(length))
        for val2 in val1.points:
          buff.write(_get_struct_i().pack(val2.id))
          _x = val2.type
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
          buff.write(_get_struct_d().pack(val2.vlimit))
          _v2 = val2.point
          _x = _v2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.special_nodes is None:
        self.special_nodes = None
      if self.special_ways is None:
        self.special_ways = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.special_nodes = []
      for i in range(0, length):
        val1 = lanelet_map_msgs.msg.Node()
        start = end
        end += 4
        (val1.id,) = _get_struct_i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.type = str[start:end].decode('utf-8')
        else:
          val1.type = str[start:end]
        start = end
        end += 8
        (val1.vlimit,) = _get_struct_d().unpack(str[start:end])
        _v3 = val1.point
        _x = _v3
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.special_nodes.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.special_ways = []
      for i in range(0, length):
        val1 = lanelet_map_msgs.msg.Way()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.task_area = str[start:end].decode('utf-8')
        else:
          val1.task_area = str[start:end]
        _x = val1
        start = end
        end += 16
        (_x.is_forward, _x.open_concave_obs_det, _x.open_dynamic_obs_det, _x.open_foggy_det, _x.open_water_det, _x.foggy_area, _x.lawn_area, _x.water_area, _x.vel_limit,) = _get_struct_8bd().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.points = []
        for i in range(0, length):
          val2 = lanelet_map_msgs.msg.Node()
          start = end
          end += 4
          (val2.id,) = _get_struct_i().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.type = str[start:end].decode('utf-8')
          else:
            val2.type = str[start:end]
          start = end
          end += 8
          (val2.vlimit,) = _get_struct_d().unpack(str[start:end])
          _v4 = val2.point
          _x = _v4
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          val1.points.append(val2)
        self.special_ways.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.special_nodes)
      buff.write(_struct_I.pack(length))
      for val1 in self.special_nodes:
        buff.write(_get_struct_i().pack(val1.id))
        _x = val1.type
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        buff.write(_get_struct_d().pack(val1.vlimit))
        _v5 = val1.point
        _x = _v5
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.special_ways)
      buff.write(_struct_I.pack(length))
      for val1 in self.special_ways:
        _x = val1.task_area
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_get_struct_8bd().pack(_x.is_forward, _x.open_concave_obs_det, _x.open_dynamic_obs_det, _x.open_foggy_det, _x.open_water_det, _x.foggy_area, _x.lawn_area, _x.water_area, _x.vel_limit))
        length = len(val1.points)
        buff.write(_struct_I.pack(length))
        for val2 in val1.points:
          buff.write(_get_struct_i().pack(val2.id))
          _x = val2.type
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
          buff.write(_get_struct_d().pack(val2.vlimit))
          _v6 = val2.point
          _x = _v6
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.special_nodes is None:
        self.special_nodes = None
      if self.special_ways is None:
        self.special_ways = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.special_nodes = []
      for i in range(0, length):
        val1 = lanelet_map_msgs.msg.Node()
        start = end
        end += 4
        (val1.id,) = _get_struct_i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.type = str[start:end].decode('utf-8')
        else:
          val1.type = str[start:end]
        start = end
        end += 8
        (val1.vlimit,) = _get_struct_d().unpack(str[start:end])
        _v7 = val1.point
        _x = _v7
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.special_nodes.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.special_ways = []
      for i in range(0, length):
        val1 = lanelet_map_msgs.msg.Way()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.task_area = str[start:end].decode('utf-8')
        else:
          val1.task_area = str[start:end]
        _x = val1
        start = end
        end += 16
        (_x.is_forward, _x.open_concave_obs_det, _x.open_dynamic_obs_det, _x.open_foggy_det, _x.open_water_det, _x.foggy_area, _x.lawn_area, _x.water_area, _x.vel_limit,) = _get_struct_8bd().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.points = []
        for i in range(0, length):
          val2 = lanelet_map_msgs.msg.Node()
          start = end
          end += 4
          (val2.id,) = _get_struct_i().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.type = str[start:end].decode('utf-8')
          else:
            val2.type = str[start:end]
          start = end
          end += 8
          (val2.vlimit,) = _get_struct_d().unpack(str[start:end])
          _v8 = val2.point
          _x = _v8
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          val1.points.append(val2)
        self.special_ways.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
_struct_8bd = None
def _get_struct_8bd():
    global _struct_8bd
    if _struct_8bd is None:
        _struct_8bd = struct.Struct("<8bd")
    return _struct_8bd
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
