// Generated by gencpp from file iv_slam_ros_msgs/StartTrajectory.msg
// DO NOT EDIT!


#ifndef IV_SLAM_ROS_MSGS_MESSAGE_STARTTRAJECTORY_H
#define IV_SLAM_ROS_MSGS_MESSAGE_STARTTRAJECTORY_H

#include <ros/service_traits.h>


#include <iv_slam_ros_msgs/StartTrajectoryRequest.h>
#include <iv_slam_ros_msgs/StartTrajectoryResponse.h>


namespace iv_slam_ros_msgs
{

struct StartTrajectory
{

typedef StartTrajectoryRequest Request;
typedef StartTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartTrajectory
} // namespace iv_slam_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iv_slam_ros_msgs::StartTrajectory > {
  static const char* value()
  {
    return "b9252ad326a557addcb36e679f2c13e4";
  }

  static const char* value(const ::iv_slam_ros_msgs::StartTrajectory&) { return value(); }
};

template<>
struct DataType< ::iv_slam_ros_msgs::StartTrajectory > {
  static const char* value()
  {
    return "iv_slam_ros_msgs/StartTrajectory";
  }

  static const char* value(const ::iv_slam_ros_msgs::StartTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::iv_slam_ros_msgs::StartTrajectoryRequest> should match 
// service_traits::MD5Sum< ::iv_slam_ros_msgs::StartTrajectory > 
template<>
struct MD5Sum< ::iv_slam_ros_msgs::StartTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iv_slam_ros_msgs::StartTrajectory >::value();
  }
  static const char* value(const ::iv_slam_ros_msgs::StartTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iv_slam_ros_msgs::StartTrajectoryRequest> should match 
// service_traits::DataType< ::iv_slam_ros_msgs::StartTrajectory > 
template<>
struct DataType< ::iv_slam_ros_msgs::StartTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::iv_slam_ros_msgs::StartTrajectory >::value();
  }
  static const char* value(const ::iv_slam_ros_msgs::StartTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iv_slam_ros_msgs::StartTrajectoryResponse> should match 
// service_traits::MD5Sum< ::iv_slam_ros_msgs::StartTrajectory > 
template<>
struct MD5Sum< ::iv_slam_ros_msgs::StartTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iv_slam_ros_msgs::StartTrajectory >::value();
  }
  static const char* value(const ::iv_slam_ros_msgs::StartTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iv_slam_ros_msgs::StartTrajectoryResponse> should match 
// service_traits::DataType< ::iv_slam_ros_msgs::StartTrajectory > 
template<>
struct DataType< ::iv_slam_ros_msgs::StartTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::iv_slam_ros_msgs::StartTrajectory >::value();
  }
  static const char* value(const ::iv_slam_ros_msgs::StartTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IV_SLAM_ROS_MSGS_MESSAGE_STARTTRAJECTORY_H
