// Generated by gencpp from file sensor_driver_msgs/PointCloudMultiLaser.msg
// DO NOT EDIT!


#ifndef SENSOR_DRIVER_MSGS_MESSAGE_POINTCLOUDMULTILASER_H
#define SENSOR_DRIVER_MSGS_MESSAGE_POINTCLOUDMULTILASER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/PointCloud2.h>

namespace sensor_driver_msgs
{
template <class ContainerAllocator>
struct PointCloudMultiLaser_
{
  typedef PointCloudMultiLaser_<ContainerAllocator> Type;

  PointCloudMultiLaser_()
    : lasernum(0)
    , lidarid(0)
    , laseridmap()
    , laseranglemap()
    , pointcloud()  {
    }
  PointCloudMultiLaser_(const ContainerAllocator& _alloc)
    : lasernum(0)
    , lidarid(0)
    , laseridmap(_alloc)
    , laseranglemap(_alloc)
    , pointcloud(_alloc)  {
  (void)_alloc;
    }



   typedef int16_t _lasernum_type;
  _lasernum_type lasernum;

   typedef int16_t _lidarid_type;
  _lidarid_type lidarid;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _laseridmap_type;
  _laseridmap_type laseridmap;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _laseranglemap_type;
  _laseranglemap_type laseranglemap;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _pointcloud_type;
  _pointcloud_type pointcloud;





  typedef boost::shared_ptr< ::sensor_driver_msgs::PointCloudMultiLaser_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_driver_msgs::PointCloudMultiLaser_<ContainerAllocator> const> ConstPtr;

}; // struct PointCloudMultiLaser_

typedef ::sensor_driver_msgs::PointCloudMultiLaser_<std::allocator<void> > PointCloudMultiLaser;

typedef boost::shared_ptr< ::sensor_driver_msgs::PointCloudMultiLaser > PointCloudMultiLaserPtr;
typedef boost::shared_ptr< ::sensor_driver_msgs::PointCloudMultiLaser const> PointCloudMultiLaserConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_driver_msgs::PointCloudMultiLaser_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_driver_msgs::PointCloudMultiLaser_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sensor_driver_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'sensor_driver_msgs': ['/home/lizhiwei/Desktop/udp_comm/src/msgs/sensor_driver_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sensor_driver_msgs::PointCloudMultiLaser_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_driver_msgs::PointCloudMultiLaser_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_driver_msgs::PointCloudMultiLaser_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_driver_msgs::PointCloudMultiLaser_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_driver_msgs::PointCloudMultiLaser_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_driver_msgs::PointCloudMultiLaser_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_driver_msgs::PointCloudMultiLaser_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af429b8dd0128bd96a7bacec1ffd7da7";
  }

  static const char* value(const ::sensor_driver_msgs::PointCloudMultiLaser_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf429b8dd0128bd9ULL;
  static const uint64_t static_value2 = 0x6a7bacec1ffd7da7ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_driver_msgs::PointCloudMultiLaser_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_driver_msgs/PointCloudMultiLaser";
  }

  static const char* value(const ::sensor_driver_msgs::PointCloudMultiLaser_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_driver_msgs::PointCloudMultiLaser_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int16 lasernum\n\
int16 lidarid\n\
int16[] laseridmap\n\
float32[] laseranglemap\n\
\n\
sensor_msgs/PointCloud2 pointcloud\n\
================================================================================\n\
MSG: sensor_msgs/PointCloud2\n\
# This message holds a collection of N-dimensional points, which may\n\
# contain additional information such as normals, intensity, etc. The\n\
# point data is stored as a binary blob, its layout described by the\n\
# contents of the \"fields\" array.\n\
\n\
# The point cloud data may be organized 2d (image-like) or 1d\n\
# (unordered). Point clouds organized as 2d images may be produced by\n\
# camera depth sensors such as stereo or time-of-flight.\n\
\n\
# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n\
# points).\n\
Header header\n\
\n\
# 2D structure of the point cloud. If the cloud is unordered, height is\n\
# 1 and width is the length of the point cloud.\n\
uint32 height\n\
uint32 width\n\
\n\
# Describes the channels and their layout in the binary data blob.\n\
PointField[] fields\n\
\n\
bool    is_bigendian # Is this data bigendian?\n\
uint32  point_step   # Length of a point in bytes\n\
uint32  row_step     # Length of a row in bytes\n\
uint8[] data         # Actual point data, size is (row_step*height)\n\
\n\
bool is_dense        # True if there are no invalid points\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointField\n\
# This message holds the description of one point entry in the\n\
# PointCloud2 message format.\n\
uint8 INT8    = 1\n\
uint8 UINT8   = 2\n\
uint8 INT16   = 3\n\
uint8 UINT16  = 4\n\
uint8 INT32   = 5\n\
uint8 UINT32  = 6\n\
uint8 FLOAT32 = 7\n\
uint8 FLOAT64 = 8\n\
\n\
string name      # Name of field\n\
uint32 offset    # Offset from start of point struct\n\
uint8  datatype  # Datatype enumeration, see above\n\
uint32 count     # How many elements in the field\n\
";
  }

  static const char* value(const ::sensor_driver_msgs::PointCloudMultiLaser_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_driver_msgs::PointCloudMultiLaser_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lasernum);
      stream.next(m.lidarid);
      stream.next(m.laseridmap);
      stream.next(m.laseranglemap);
      stream.next(m.pointcloud);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointCloudMultiLaser_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_driver_msgs::PointCloudMultiLaser_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_driver_msgs::PointCloudMultiLaser_<ContainerAllocator>& v)
  {
    s << indent << "lasernum: ";
    Printer<int16_t>::stream(s, indent + "  ", v.lasernum);
    s << indent << "lidarid: ";
    Printer<int16_t>::stream(s, indent + "  ", v.lidarid);
    s << indent << "laseridmap[]" << std::endl;
    for (size_t i = 0; i < v.laseridmap.size(); ++i)
    {
      s << indent << "  laseridmap[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.laseridmap[i]);
    }
    s << indent << "laseranglemap[]" << std::endl;
    for (size_t i = 0; i < v.laseranglemap.size(); ++i)
    {
      s << indent << "  laseranglemap[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.laseranglemap[i]);
    }
    s << indent << "pointcloud: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.pointcloud);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_DRIVER_MSGS_MESSAGE_POINTCLOUDMULTILASER_H
