(cl:defpackage sensor_driver_msgs-msg
  (:use )
  (:export
   "<ECUDATA>"
   "ECUDATA"
   "<GPSWITHHEADING>"
   "GPSWITHHEADING"
   "<GPSWITHTIME>"
   "GPSWITHTIME"
   "<INSVELOCITY>"
   "INSVELOCITY"
   "<ODOMETRYWITHGPS>"
   "ODOMETRYWITHGPS"
   "<POINTCLOUDMULTILASER>"
   "POINTCLOUDMULTILASER"
   "<POINTCLOUDMULTILIDAR>"
   "POINTCLOUDMULTILIDAR"
   "<POINTS>"
   "POINTS"
   "<RECTANGLE>"
   "RECTANGLE"
   "<TARGETCAR>"
   "TARGETCAR"
   "<MOVING_TARGET>"
   "MOVING_TARGET"
   "<MOVING_TARGET_SEND>"
   "MOVING_TARGET_SEND"
  ))

