(cl:in-package sensor_driver_msgs-msg)
(cl:export '(CENTER_X-VAL
          CENTER_X
          CENTER_Y-VAL
          CENTER_Y
          OBJECT_WIDTH-VAL
          OBJECT_WIDTH
          OBJECT_LENGTH-VAL
          OBJECT_LENGTH
          OBJECT_HIGH-VAL
          OBJECT_HIGH
          OBJECT_RECT_X-VAL
          OBJECT_RECT_X
          OBJECT_RECT_Y-VAL
          OBJECT_RECT_Y
          OBJECT_RECT_WIDTH-VAL
          OBJECT_RECT_WIDTH
          OBJECT_RECT_HEIGHT-VAL
          OBJECT_RECT_HEIGHT
          X_SRC-VAL
          X_SRC
          Y_SRC-VAL
          Y_SRC
          V_X-VAL
          V_X
          V_Y-VAL
          V_Y
          V-VAL
          V
          V_THETA-VAL
          V_THETA
          POS_HEADING-VAL
          POS_HEADING
          V_W-VAL
          V_W
          TRACKPOINT32_INDEX-VAL
          TRACKPOINT32_INDEX
          FILTER_METHOD-VAL
          FILTER_METHOD
          IS_UPDATED-VAL
          IS_UPDATED
          TIME_STAMP-VAL
          TIME_STAMP
          ID_NUMBER-VAL
          ID_NUMBER
          CONFIDENCE_LEVEL-VAL
          CONFIDENCE_LEVEL
          TRACKED_TIMES-VAL
          TRACKED_TIMES
          MISS_TRACKED_TIMES-VAL
          MISS_TRACKED_TIMES
          DIS_VEH_XY-VAL
          DIS_VEH_XY
          POSITION_ORIENTATION-VAL
          POSITION_ORIENTATION
          OCCLUDED_STATE-VAL
          OCCLUDED_STATE
          OBJECT_TYPE-VAL
          OBJECT_TYPE
          DANGEROUS_LEVEL-VAL
          DANGEROUS_LEVEL
          TRACKPOINT_INDEX-VAL
          TRACKPOINT_INDEX
))