(cl:in-package sensor_driver_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          F_SHIFT-VAL
          F_SHIFT
          F_SHIFT1-VAL
          F_SHIFT1
          FDEFORWARDVEL-VAL
          FDEFORWARDVEL
          FFLRWHEELAVERANGLE-VAL
          FFLRWHEELAVERANGLE
          FFORWARDVEL-VAL
          FFORWARDVEL
          PETRAL_PRESSURE-VAL
          PETRAL_PRESSURE
          PRESSURE_BACK-VAL
          PRESSURE_BACK
          FRONTLEFTWHEELSPEED-VAL
          FRONTLEFTWHEELSPEED
          FRONTRIGHTWHEELSPEED-VAL
          FRONTRIGHTWHEELSPEED
          BACKLEFTWHEELSPEED-VAL
          BACKLEFTWHEELSPEED
          BACKRIGHTWHEELSPEED-VAL
          BACKRIGHTWHEELSPEED
          MOTOR_I_L-VAL
          MOTOR_I_L
          MOTOR_I_R-VAL
          MOTOR_I_R
          MOTOR_TORQUE_L-VAL
          MOTOR_TORQUE_L
          MOTOR_TORQUE_R-VAL
          MOTOR_TORQUE_R
          MOTOR_U_L-VAL
          MOTOR_U_L
          MOTOR_U_R-VAL
          MOTOR_U_R
          MOTOR_N_NOW_L-VAL
          MOTOR_N_NOW_L
          MOTOR_N_NOW_R-VAL
          MOTOR_N_NOW_R
          GEAR_STATE_NOW-VAL
          GEAR_STATE_NOW
          STEER_DEGREE_NOW-VAL
          STEER_DEGREE_NOW
          STEER_DIRECTION_NOW-VAL
          STEER_DIRECTION_NOW
          SOC_NOW-VAL
          SOC_NOW
))