// Generated by gencpp from file speed_debug_msgs/v.msg
// DO NOT EDIT!


#ifndef SPEED_DEBUG_MSGS_MESSAGE_V_H
#define SPEED_DEBUG_MSGS_MESSAGE_V_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace speed_debug_msgs
{
template <class ContainerAllocator>
struct v_
{
  typedef v_<ContainerAllocator> Type;

  v_()
    : v_max_dynamic(0.0)
    , v_lat_acc(0.0)
    , v_lon_acc(0.0)
    , v_slide_dec(0.0)
    , v_lon_dec(0.0)
    , v_jerk(0.0)
    , v_blind(0.0)
    , v_constrained(0.0)  {
    }
  v_(const ContainerAllocator& _alloc)
    : v_max_dynamic(0.0)
    , v_lat_acc(0.0)
    , v_lon_acc(0.0)
    , v_slide_dec(0.0)
    , v_lon_dec(0.0)
    , v_jerk(0.0)
    , v_blind(0.0)
    , v_constrained(0.0)  {
  (void)_alloc;
    }



   typedef double _v_max_dynamic_type;
  _v_max_dynamic_type v_max_dynamic;

   typedef double _v_lat_acc_type;
  _v_lat_acc_type v_lat_acc;

   typedef double _v_lon_acc_type;
  _v_lon_acc_type v_lon_acc;

   typedef double _v_slide_dec_type;
  _v_slide_dec_type v_slide_dec;

   typedef double _v_lon_dec_type;
  _v_lon_dec_type v_lon_dec;

   typedef double _v_jerk_type;
  _v_jerk_type v_jerk;

   typedef double _v_blind_type;
  _v_blind_type v_blind;

   typedef double _v_constrained_type;
  _v_constrained_type v_constrained;





  typedef boost::shared_ptr< ::speed_debug_msgs::v_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::speed_debug_msgs::v_<ContainerAllocator> const> ConstPtr;

}; // struct v_

typedef ::speed_debug_msgs::v_<std::allocator<void> > v;

typedef boost::shared_ptr< ::speed_debug_msgs::v > vPtr;
typedef boost::shared_ptr< ::speed_debug_msgs::v const> vConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::speed_debug_msgs::v_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::speed_debug_msgs::v_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace speed_debug_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'speed_debug_msgs': ['/home/lizhiwei/Desktop/udp_comm/src/msgs/speed_debug_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::speed_debug_msgs::v_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::speed_debug_msgs::v_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speed_debug_msgs::v_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speed_debug_msgs::v_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speed_debug_msgs::v_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speed_debug_msgs::v_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::speed_debug_msgs::v_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2bb18dd6157ad5bbbd8073687e75001e";
  }

  static const char* value(const ::speed_debug_msgs::v_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2bb18dd6157ad5bbULL;
  static const uint64_t static_value2 = 0xbd8073687e75001eULL;
};

template<class ContainerAllocator>
struct DataType< ::speed_debug_msgs::v_<ContainerAllocator> >
{
  static const char* value()
  {
    return "speed_debug_msgs/v";
  }

  static const char* value(const ::speed_debug_msgs::v_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::speed_debug_msgs::v_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 v_max_dynamic\n\
float64 v_lat_acc\n\
float64 v_lon_acc\n\
float64 v_slide_dec\n\
float64 v_lon_dec\n\
float64 v_jerk\n\
float64 v_blind\n\
float64 v_constrained\n\
";
  }

  static const char* value(const ::speed_debug_msgs::v_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::speed_debug_msgs::v_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.v_max_dynamic);
      stream.next(m.v_lat_acc);
      stream.next(m.v_lon_acc);
      stream.next(m.v_slide_dec);
      stream.next(m.v_lon_dec);
      stream.next(m.v_jerk);
      stream.next(m.v_blind);
      stream.next(m.v_constrained);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct v_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::speed_debug_msgs::v_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::speed_debug_msgs::v_<ContainerAllocator>& v)
  {
    s << indent << "v_max_dynamic: ";
    Printer<double>::stream(s, indent + "  ", v.v_max_dynamic);
    s << indent << "v_lat_acc: ";
    Printer<double>::stream(s, indent + "  ", v.v_lat_acc);
    s << indent << "v_lon_acc: ";
    Printer<double>::stream(s, indent + "  ", v.v_lon_acc);
    s << indent << "v_slide_dec: ";
    Printer<double>::stream(s, indent + "  ", v.v_slide_dec);
    s << indent << "v_lon_dec: ";
    Printer<double>::stream(s, indent + "  ", v.v_lon_dec);
    s << indent << "v_jerk: ";
    Printer<double>::stream(s, indent + "  ", v.v_jerk);
    s << indent << "v_blind: ";
    Printer<double>::stream(s, indent + "  ", v.v_blind);
    s << indent << "v_constrained: ";
    Printer<double>::stream(s, indent + "  ", v.v_constrained);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPEED_DEBUG_MSGS_MESSAGE_V_H
