(cl:in-package speed_ctrl_msgs-msg)
(cl:export '(DIRECTION-VAL
          DIRECTION
          COUNT-VAL
          COUNT
          ISSUE_ACC-VAL
          ISSUE_ACC
          ISSUE_V-VAL
          ISSUE_V
          CUR_ACC-VAL
          CUR_ACC
          CUR_SPEED-VAL
          CUR_SPEED
          RC_PATH_TIME-VAL
          RC_PATH_TIME
          PUB_ACC_TIME-VAL
          PUB_ACC_TIME
          RC_ACC_TIME-VAL
          RC_ACC_TIME
          PUB_CMD_TIME-VAL
          PUB_CMD_TIME
          TOTAL_S-VAL
          TOTAL_S
          CURV_MAX-VAL
          CURV_MAX
          V_MAX-VAL
          V_MAX
          RUNNING_MODE-VAL
          RUNNING_MODE
))