# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from iv_dynamicobject_msgs/moving_target_send.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import iv_dynamicobject_msgs.msg

class moving_target_send(genpy.Message):
  _md5sum = "52c14969bef6f78128016409bcbd38ec"
  _type = "iv_dynamicobject_msgs/moving_target_send"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 time_stamp        
int32 target_num
moving_target[] target          

================================================================================
MSG: iv_dynamicobject_msgs/moving_target
    int32 ID_number
    Points center_point
    int32 line_num
    Points[] line_point   
    float32 object_high
    int32 object_type    
    bool is_updated
    int32  tracked_times
    int32  dangerous_level
    int32  history_num
    History_traj[] history_traj
    int32  predict_num
    Predict_traj[] predict_traj       

================================================================================
MSG: iv_dynamicobject_msgs/Points
float64 x
float64 y
float64 z

================================================================================
MSG: iv_dynamicobject_msgs/History_traj
    float64 time_stamp
    Points center_point
    int32 line_num
    Points[] line_point
    

================================================================================
MSG: iv_dynamicobject_msgs/Predict_traj
    float64 time_stamp
    Points point
    float32 v_x
    float32 v_y
    float32 acc_x
    float32 acc_y
    float32 pos_head
    float32 v_w
    int16 confidence_level
"""
  __slots__ = ['time_stamp','target_num','target']
  _slot_types = ['float64','int32','iv_dynamicobject_msgs/moving_target[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       time_stamp,target_num,target

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(moving_target_send, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.time_stamp is None:
        self.time_stamp = 0.
      if self.target_num is None:
        self.target_num = 0
      if self.target is None:
        self.target = []
    else:
      self.time_stamp = 0.
      self.target_num = 0
      self.target = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_di().pack(_x.time_stamp, _x.target_num))
      length = len(self.target)
      buff.write(_struct_I.pack(length))
      for val1 in self.target:
        buff.write(_get_struct_i().pack(val1.ID_number))
        _v1 = val1.center_point
        _x = _v1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        buff.write(_get_struct_i().pack(val1.line_num))
        length = len(val1.line_point)
        buff.write(_struct_I.pack(length))
        for val2 in val1.line_point:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1
        buff.write(_get_struct_fiB3i().pack(_x.object_high, _x.object_type, _x.is_updated, _x.tracked_times, _x.dangerous_level, _x.history_num))
        length = len(val1.history_traj)
        buff.write(_struct_I.pack(length))
        for val2 in val1.history_traj:
          buff.write(_get_struct_d().pack(val2.time_stamp))
          _v2 = val2.center_point
          _x = _v2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          buff.write(_get_struct_i().pack(val2.line_num))
          length = len(val2.line_point)
          buff.write(_struct_I.pack(length))
          for val3 in val2.line_point:
            _x = val3
            buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        buff.write(_get_struct_i().pack(val1.predict_num))
        length = len(val1.predict_traj)
        buff.write(_struct_I.pack(length))
        for val2 in val1.predict_traj:
          buff.write(_get_struct_d().pack(val2.time_stamp))
          _v3 = val2.point
          _x = _v3
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _x = val2
          buff.write(_get_struct_6fh().pack(_x.v_x, _x.v_y, _x.acc_x, _x.acc_y, _x.pos_head, _x.v_w, _x.confidence_level))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.target is None:
        self.target = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.time_stamp, _x.target_num,) = _get_struct_di().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.target = []
      for i in range(0, length):
        val1 = iv_dynamicobject_msgs.msg.moving_target()
        start = end
        end += 4
        (val1.ID_number,) = _get_struct_i().unpack(str[start:end])
        _v4 = val1.center_point
        _x = _v4
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 4
        (val1.line_num,) = _get_struct_i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.line_point = []
        for i in range(0, length):
          val2 = iv_dynamicobject_msgs.msg.Points()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          val1.line_point.append(val2)
        _x = val1
        start = end
        end += 21
        (_x.object_high, _x.object_type, _x.is_updated, _x.tracked_times, _x.dangerous_level, _x.history_num,) = _get_struct_fiB3i().unpack(str[start:end])
        val1.is_updated = bool(val1.is_updated)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.history_traj = []
        for i in range(0, length):
          val2 = iv_dynamicobject_msgs.msg.History_traj()
          start = end
          end += 8
          (val2.time_stamp,) = _get_struct_d().unpack(str[start:end])
          _v5 = val2.center_point
          _x = _v5
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (val2.line_num,) = _get_struct_i().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val2.line_point = []
          for i in range(0, length):
            val3 = iv_dynamicobject_msgs.msg.Points()
            _x = val3
            start = end
            end += 24
            (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
            val2.line_point.append(val3)
          val1.history_traj.append(val2)
        start = end
        end += 4
        (val1.predict_num,) = _get_struct_i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.predict_traj = []
        for i in range(0, length):
          val2 = iv_dynamicobject_msgs.msg.Predict_traj()
          start = end
          end += 8
          (val2.time_stamp,) = _get_struct_d().unpack(str[start:end])
          _v6 = val2.point
          _x = _v6
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _x = val2
          start = end
          end += 26
          (_x.v_x, _x.v_y, _x.acc_x, _x.acc_y, _x.pos_head, _x.v_w, _x.confidence_level,) = _get_struct_6fh().unpack(str[start:end])
          val1.predict_traj.append(val2)
        self.target.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_di().pack(_x.time_stamp, _x.target_num))
      length = len(self.target)
      buff.write(_struct_I.pack(length))
      for val1 in self.target:
        buff.write(_get_struct_i().pack(val1.ID_number))
        _v7 = val1.center_point
        _x = _v7
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        buff.write(_get_struct_i().pack(val1.line_num))
        length = len(val1.line_point)
        buff.write(_struct_I.pack(length))
        for val2 in val1.line_point:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1
        buff.write(_get_struct_fiB3i().pack(_x.object_high, _x.object_type, _x.is_updated, _x.tracked_times, _x.dangerous_level, _x.history_num))
        length = len(val1.history_traj)
        buff.write(_struct_I.pack(length))
        for val2 in val1.history_traj:
          buff.write(_get_struct_d().pack(val2.time_stamp))
          _v8 = val2.center_point
          _x = _v8
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          buff.write(_get_struct_i().pack(val2.line_num))
          length = len(val2.line_point)
          buff.write(_struct_I.pack(length))
          for val3 in val2.line_point:
            _x = val3
            buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        buff.write(_get_struct_i().pack(val1.predict_num))
        length = len(val1.predict_traj)
        buff.write(_struct_I.pack(length))
        for val2 in val1.predict_traj:
          buff.write(_get_struct_d().pack(val2.time_stamp))
          _v9 = val2.point
          _x = _v9
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _x = val2
          buff.write(_get_struct_6fh().pack(_x.v_x, _x.v_y, _x.acc_x, _x.acc_y, _x.pos_head, _x.v_w, _x.confidence_level))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.target is None:
        self.target = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.time_stamp, _x.target_num,) = _get_struct_di().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.target = []
      for i in range(0, length):
        val1 = iv_dynamicobject_msgs.msg.moving_target()
        start = end
        end += 4
        (val1.ID_number,) = _get_struct_i().unpack(str[start:end])
        _v10 = val1.center_point
        _x = _v10
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 4
        (val1.line_num,) = _get_struct_i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.line_point = []
        for i in range(0, length):
          val2 = iv_dynamicobject_msgs.msg.Points()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          val1.line_point.append(val2)
        _x = val1
        start = end
        end += 21
        (_x.object_high, _x.object_type, _x.is_updated, _x.tracked_times, _x.dangerous_level, _x.history_num,) = _get_struct_fiB3i().unpack(str[start:end])
        val1.is_updated = bool(val1.is_updated)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.history_traj = []
        for i in range(0, length):
          val2 = iv_dynamicobject_msgs.msg.History_traj()
          start = end
          end += 8
          (val2.time_stamp,) = _get_struct_d().unpack(str[start:end])
          _v11 = val2.center_point
          _x = _v11
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (val2.line_num,) = _get_struct_i().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val2.line_point = []
          for i in range(0, length):
            val3 = iv_dynamicobject_msgs.msg.Points()
            _x = val3
            start = end
            end += 24
            (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
            val2.line_point.append(val3)
          val1.history_traj.append(val2)
        start = end
        end += 4
        (val1.predict_num,) = _get_struct_i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.predict_traj = []
        for i in range(0, length):
          val2 = iv_dynamicobject_msgs.msg.Predict_traj()
          start = end
          end += 8
          (val2.time_stamp,) = _get_struct_d().unpack(str[start:end])
          _v12 = val2.point
          _x = _v12
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _x = val2
          start = end
          end += 26
          (_x.v_x, _x.v_y, _x.acc_x, _x.acc_y, _x.pos_head, _x.v_w, _x.confidence_level,) = _get_struct_6fh().unpack(str[start:end])
          val1.predict_traj.append(val2)
        self.target.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
_struct_6fh = None
def _get_struct_6fh():
    global _struct_6fh
    if _struct_6fh is None:
        _struct_6fh = struct.Struct("<6fh")
    return _struct_6fh
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
_struct_di = None
def _get_struct_di():
    global _struct_di
    if _struct_di is None:
        _struct_di = struct.Struct("<di")
    return _struct_di
_struct_fiB3i = None
def _get_struct_fiB3i():
    global _struct_fiB3i
    if _struct_fiB3i is None:
        _struct_fiB3i = struct.Struct("<fiB3i")
    return _struct_fiB3i
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
