// Generated by gencpp from file dymidetect2speed_msgs/Dymipoint.msg
// DO NOT EDIT!


#ifndef DYMIDETECT2SPEED_MSGS_MESSAGE_DYMIPOINT_H
#define DYMIDETECT2SPEED_MSGS_MESSAGE_DYMIPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace dymidetect2speed_msgs
{
template <class ContainerAllocator>
struct Dymipoint_
{
  typedef Dymipoint_<ContainerAllocator> Type;

  Dymipoint_()
    : position()  {
    }
  Dymipoint_(const ContainerAllocator& _alloc)
    : position(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::dymidetect2speed_msgs::Dymipoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dymidetect2speed_msgs::Dymipoint_<ContainerAllocator> const> ConstPtr;

}; // struct Dymipoint_

typedef ::dymidetect2speed_msgs::Dymipoint_<std::allocator<void> > Dymipoint;

typedef boost::shared_ptr< ::dymidetect2speed_msgs::Dymipoint > DymipointPtr;
typedef boost::shared_ptr< ::dymidetect2speed_msgs::Dymipoint const> DymipointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dymidetect2speed_msgs::Dymipoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dymidetect2speed_msgs::Dymipoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dymidetect2speed_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'dymidetect2speed_msgs': ['/home/lizhiwei/Desktop/udp_comm/src/msgs/dymidetect2speed_msgs/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dymidetect2speed_msgs::Dymipoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dymidetect2speed_msgs::Dymipoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dymidetect2speed_msgs::Dymipoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dymidetect2speed_msgs::Dymipoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dymidetect2speed_msgs::Dymipoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dymidetect2speed_msgs::Dymipoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dymidetect2speed_msgs::Dymipoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7bb0ef028c744b081acdc57743b11d8";
  }

  static const char* value(const ::dymidetect2speed_msgs::Dymipoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7bb0ef028c744b0ULL;
  static const uint64_t static_value2 = 0x81acdc57743b11d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::dymidetect2speed_msgs::Dymipoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dymidetect2speed_msgs/Dymipoint";
  }

  static const char* value(const ::dymidetect2speed_msgs::Dymipoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dymidetect2speed_msgs::Dymipoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point position\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::dymidetect2speed_msgs::Dymipoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dymidetect2speed_msgs::Dymipoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Dymipoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dymidetect2speed_msgs::Dymipoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dymidetect2speed_msgs::Dymipoint_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYMIDETECT2SPEED_MSGS_MESSAGE_DYMIPOINT_H
