// Generated by gencpp from file dymidetect2speed_msgs/Dymipoints.msg
// DO NOT EDIT!


#ifndef DYMIDETECT2SPEED_MSGS_MESSAGE_DYMIPOINTS_H
#define DYMIDETECT2SPEED_MSGS_MESSAGE_DYMIPOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <dymidetect2speed_msgs/Dymipoint.h>

namespace dymidetect2speed_msgs
{
template <class ContainerAllocator>
struct Dymipoints_
{
  typedef Dymipoints_<ContainerAllocator> Type;

  Dymipoints_()
    : header()
    , dymipoints()  {
    }
  Dymipoints_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , dymipoints(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::dymidetect2speed_msgs::Dymipoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::dymidetect2speed_msgs::Dymipoint_<ContainerAllocator> >::other >  _dymipoints_type;
  _dymipoints_type dymipoints;





  typedef boost::shared_ptr< ::dymidetect2speed_msgs::Dymipoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dymidetect2speed_msgs::Dymipoints_<ContainerAllocator> const> ConstPtr;

}; // struct Dymipoints_

typedef ::dymidetect2speed_msgs::Dymipoints_<std::allocator<void> > Dymipoints;

typedef boost::shared_ptr< ::dymidetect2speed_msgs::Dymipoints > DymipointsPtr;
typedef boost::shared_ptr< ::dymidetect2speed_msgs::Dymipoints const> DymipointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dymidetect2speed_msgs::Dymipoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dymidetect2speed_msgs::Dymipoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dymidetect2speed_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'dymidetect2speed_msgs': ['/home/lizhiwei/Desktop/udp_comm/src/msgs/dymidetect2speed_msgs/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dymidetect2speed_msgs::Dymipoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dymidetect2speed_msgs::Dymipoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dymidetect2speed_msgs::Dymipoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dymidetect2speed_msgs::Dymipoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dymidetect2speed_msgs::Dymipoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dymidetect2speed_msgs::Dymipoints_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dymidetect2speed_msgs::Dymipoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f332c1b2f057ff022a7fac3fdfcee363";
  }

  static const char* value(const ::dymidetect2speed_msgs::Dymipoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf332c1b2f057ff02ULL;
  static const uint64_t static_value2 = 0x2a7fac3fdfcee363ULL;
};

template<class ContainerAllocator>
struct DataType< ::dymidetect2speed_msgs::Dymipoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dymidetect2speed_msgs/Dymipoints";
  }

  static const char* value(const ::dymidetect2speed_msgs::Dymipoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dymidetect2speed_msgs::Dymipoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
Dymipoint[] dymipoints\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: dymidetect2speed_msgs/Dymipoint\n\
geometry_msgs/Point position\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::dymidetect2speed_msgs::Dymipoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dymidetect2speed_msgs::Dymipoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.dymipoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Dymipoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dymidetect2speed_msgs::Dymipoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dymidetect2speed_msgs::Dymipoints_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "dymipoints[]" << std::endl;
    for (size_t i = 0; i < v.dymipoints.size(); ++i)
    {
      s << indent << "  dymipoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::dymidetect2speed_msgs::Dymipoint_<ContainerAllocator> >::stream(s, indent + "    ", v.dymipoints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYMIDETECT2SPEED_MSGS_MESSAGE_DYMIPOINTS_H
