(cl:in-package control_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          MODE-VAL
          MODE
          STEER_CUR-VAL
          STEER_CUR
          SHIFT_CUR-VAL
          SHIFT_CUR
          SHIFT1_CUR-VAL
          SHIFT1_CUR
          BRAKE_CUR-VAL
          BRAKE_CUR
          THROTTLE_CUR-VAL
          THROTTLE_CUR
          SPEED-VAL
          SPEED
          MANUAL-VAL
          MANUAL
          APU_U-VAL
          APU_U
          APU_I-VAL
          APU_I
          BATTERY_I-VAL
          BATTERY_I
          BATTERY_U-VAL
          BATTERY_U
          POWER_DEMAND-VAL
          POWER_DEMAND
          MOTOR_I_L-VAL
          MOTOR_I_L
          MOTOR_I_R-VAL
          MOTOR_I_R
          MOTOR_TORQUE_L-VAL
          MOTOR_TORQUE_L
          MOTOR_TORQUE_R-VAL
          MOTOR_TORQUE_R
          MOTOR_U_L-VAL
          MOTOR_U_L
          MOTOR_U_R-VAL
          MOTOR_U_R
          MOTOR_N_NOW_L-VAL
          MOTOR_N_NOW_L
          MOTOR_N_NOW_R-VAL
          MOTOR_N_NOW_R
          GEAR_STATE_NOW_L-VAL
          GEAR_STATE_NOW_L
          GEAR_STATE_NOW_R-VAL
          GEAR_STATE_NOW_R
          STEER_DEGREE_NOW-VAL
          STEER_DEGREE_NOW
          STEER_DIRECTION_NOW-VAL
          STEER_DIRECTION_NOW
          SOC_NOW-VAL
          SOC_NOW
))