(cl:in-package control_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          F_SHIFT-VAL
          F_SHIFT
          F_SHIFT1-VAL
          F_SHIFT1
          FDEFORWARDVEL-VAL
          FDEFORWARDVEL
          FFLRWHEELAVERANGLE-VAL
          FFLRWHEELAVERANGLE
          FFORWARDVEL-VAL
          FFORWARDVEL
          PETRAL_PRESSURE-VAL
          PETRAL_PRESSURE
          PRESSURE_BACK-VAL
          PRESSURE_BACK
          FRONTLEFTWHEELSPEED-VAL
          FRONTLEFTWHEELSPEED
          FRONTRIGHTWHEELSPEED-VAL
          FRONTRIGHTWHEELSPEED
          BACKLEFTWHEELSPEED-VAL
          BACKLEFTWHEELSPEED
          BACKRIGHTWHEELSPEED-VAL
          BACKRIGHTWHEELSPEED
))