(cl:defpackage iv_slam_ros_msgs-msg
  (:use )
  (:export
   "<DYMIPOINT>"
   "DYMIPOINT"
   "<DYMIPOINTS>"
   "DYMIPOINTS"
   "<SENSORTOPICS>"
   "SENSORTOPICS"
   "<SUBMAPENTRY>"
   "SUBMAPENTRY"
   "<SUBMAPINDEX>"
   "SUBMAPINDEX"
   "<SUBMAPLIST>"
   "SUBMAPLIST"
   "<TRAJECTORYOPTIONS>"
   "TRAJECTORYOPTIONS"
   "<TRAVERSABLEAREA>"
   "TRAVERSABLEAREA"
   "<TRAVERSIBLEAREA>"
   "TRAVERSIBLEAREA"
   "<INSERTION_SUBMAPS>"
   "INSERTION_SUBMAPS"
  ))

