// Generated by gencpp from file control_msgs/SteerCmd.msg
// DO NOT EDIT!


#ifndef CONTROL_MSGS_MESSAGE_STEERCMD_H
#define CONTROL_MSGS_MESSAGE_STEERCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace control_msgs
{
template <class ContainerAllocator>
struct SteerCmd_
{
  typedef SteerCmd_<ContainerAllocator> Type;

  SteerCmd_()
    : header()
    , steer(0.0)
    , direction(0.0)
    , vel_six(0.0)  {
    }
  SteerCmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , steer(0.0)
    , direction(0.0)
    , vel_six(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _steer_type;
  _steer_type steer;

   typedef float _direction_type;
  _direction_type direction;

   typedef float _vel_six_type;
  _vel_six_type vel_six;





  typedef boost::shared_ptr< ::control_msgs::SteerCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_msgs::SteerCmd_<ContainerAllocator> const> ConstPtr;

}; // struct SteerCmd_

typedef ::control_msgs::SteerCmd_<std::allocator<void> > SteerCmd;

typedef boost::shared_ptr< ::control_msgs::SteerCmd > SteerCmdPtr;
typedef boost::shared_ptr< ::control_msgs::SteerCmd const> SteerCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_msgs::SteerCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_msgs::SteerCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace control_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_driver_msgs': ['/home/lizhiwei/Desktop/udp_comm/src/msgs/sensor_driver_msgs/msg'], 'control_msgs': ['/home/lizhiwei/Desktop/udp_comm/src/msgs/control_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::control_msgs::SteerCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_msgs::SteerCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_msgs::SteerCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_msgs::SteerCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_msgs::SteerCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_msgs::SteerCmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_msgs::SteerCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e76a500f94dff12a77baba64a0bbd169";
  }

  static const char* value(const ::control_msgs::SteerCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe76a500f94dff12aULL;
  static const uint64_t static_value2 = 0x77baba64a0bbd169ULL;
};

template<class ContainerAllocator>
struct DataType< ::control_msgs::SteerCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_msgs/SteerCmd";
  }

  static const char* value(const ::control_msgs::SteerCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_msgs::SteerCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 steer\n\
float32 direction\n\
float32 vel_six\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::control_msgs::SteerCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_msgs::SteerCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.steer);
      stream.next(m.direction);
      stream.next(m.vel_six);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SteerCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_msgs::SteerCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_msgs::SteerCmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "steer: ";
    Printer<float>::stream(s, indent + "  ", v.steer);
    s << indent << "direction: ";
    Printer<float>::stream(s, indent + "  ", v.direction);
    s << indent << "vel_six: ";
    Printer<float>::stream(s, indent + "  ", v.vel_six);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_MSGS_MESSAGE_STEERCMD_H
