// Generated by gencpp from file control_msgs/ThrottleReport.msg
// DO NOT EDIT!


#ifndef CONTROL_MSGS_MESSAGE_THROTTLEREPORT_H
#define CONTROL_MSGS_MESSAGE_THROTTLEREPORT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <control_msgs/EngineReport.h>

namespace control_msgs
{
template <class ContainerAllocator>
struct ThrottleReport_
{
  typedef ThrottleReport_<ContainerAllocator> Type;

  ThrottleReport_()
    : header()
    , throttle(0.0)
    , engine_status()
    , throttle_pedal(0.0)  {
    }
  ThrottleReport_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , throttle(0.0)
    , engine_status(_alloc)
    , throttle_pedal(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _throttle_type;
  _throttle_type throttle;

   typedef  ::control_msgs::EngineReport_<ContainerAllocator>  _engine_status_type;
  _engine_status_type engine_status;

   typedef float _throttle_pedal_type;
  _throttle_pedal_type throttle_pedal;





  typedef boost::shared_ptr< ::control_msgs::ThrottleReport_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_msgs::ThrottleReport_<ContainerAllocator> const> ConstPtr;

}; // struct ThrottleReport_

typedef ::control_msgs::ThrottleReport_<std::allocator<void> > ThrottleReport;

typedef boost::shared_ptr< ::control_msgs::ThrottleReport > ThrottleReportPtr;
typedef boost::shared_ptr< ::control_msgs::ThrottleReport const> ThrottleReportConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_msgs::ThrottleReport_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_msgs::ThrottleReport_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace control_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_driver_msgs': ['/home/lizhiwei/Desktop/udp_comm/src/msgs/sensor_driver_msgs/msg'], 'control_msgs': ['/home/lizhiwei/Desktop/udp_comm/src/msgs/control_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::control_msgs::ThrottleReport_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_msgs::ThrottleReport_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_msgs::ThrottleReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_msgs::ThrottleReport_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_msgs::ThrottleReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_msgs::ThrottleReport_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_msgs::ThrottleReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "daef74a19d1d312c3656ecf3c3a9c5ee";
  }

  static const char* value(const ::control_msgs::ThrottleReport_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdaef74a19d1d312cULL;
  static const uint64_t static_value2 = 0x3656ecf3c3a9c5eeULL;
};

template<class ContainerAllocator>
struct DataType< ::control_msgs::ThrottleReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_msgs/ThrottleReport";
  }

  static const char* value(const ::control_msgs::ThrottleReport_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_msgs::ThrottleReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 throttle\n\
control_msgs/EngineReport engine_status\n\
float32 throttle_pedal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: control_msgs/EngineReport\n\
Header header\n\
float32 engine_rpm\n\
float32 engine_load\n\
";
  }

  static const char* value(const ::control_msgs::ThrottleReport_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_msgs::ThrottleReport_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.throttle);
      stream.next(m.engine_status);
      stream.next(m.throttle_pedal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ThrottleReport_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_msgs::ThrottleReport_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_msgs::ThrottleReport_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "throttle: ";
    Printer<float>::stream(s, indent + "  ", v.throttle);
    s << indent << "engine_status: ";
    s << std::endl;
    Printer< ::control_msgs::EngineReport_<ContainerAllocator> >::stream(s, indent + "  ", v.engine_status);
    s << indent << "throttle_pedal: ";
    Printer<float>::stream(s, indent + "  ", v.throttle_pedal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_MSGS_MESSAGE_THROTTLEREPORT_H
